//<autogenerated> - Don't edit!

function POMeasured_DoOneMinute()
{
	var res = SeSPageObjectRvlInvoke(
		this,
		__dirname+"\\Test.sstest",
		__dirname+"\\Main.rvl.xlsx",
		"DoOneMinute",
		{
		}
	);
	return res;
}

var _paramInfoPOMeasured_DoOneMinute={
	"_description": "DoOneMinute description",
	"_type": "object",
	"_returns": "",
	"ReturnValue": {
		"type": "object"
	}
};

SeSPageObject("POMeasured");
